### ISSUE TITLE
fork babel-ramda-plugin

### ISSUE THREAD

**Issue by aizerin** [tommmyy/ramda-extension#118] opened 2018-09-17 12:48 UTC
fork this plugin https://www.npmjs.com/package/babel-plugin-ramda-patch. And make it work for ramda-extension

**Comment by wafflepie** [comment] 2018-09-24 12:12
I believe that this plugin exists mainly because current Ramda version does not have `sideEffects: false` in `package.json` (it only has `side-effects: false` which is absolutely useless). This will be fixed in 0.26.0.

We should definitely add `sideEffects: false` for free treeshaking in all webpack projects. Forking this plugin would add treeshaking to non-webpack projects as well, but I'm not sure if it's worth the time.

**Comment by tommmyy** [comment] 2018-09-24 12:14
@wafflepie will you push PR?

**Comment by tommmyy** [comment] 2018-09-24 12:36
@wafflepie Thank you!

**Comment by wafflepie** [comment] 2018-09-24 12:48
Sadly, it won't be that easy – webpack still attempts to import the  entire `es/ramda-extensions.js` file. If I remove `"module": "es/ramda-extension.js"` and set `main` to `src/index.js`, it works as intended.

I'm not very good with rollup, but if I remember correctly, `react-union` used to have multiple files in the `es` folder, not just one. This is precisely what we need.

**Comment by tommmyy** [comment] 2018-09-24 12:52
I don't think that "es" build is needed - but you can check it in ramda's repo or even in redux repo.

**Comment by aizerin** [comment] 2018-09-24 13:00
@wafflepie I'm not sure if webpack's `sideEffects` works correctly. I've tried it with Ramda (I've changed the package.json for fix) and it still includes everything from index.js. But there may be problem with the build of Ramda or my setup.

**Comment by wafflepie** [comment] 2018-09-24 13:15
It should work correctly – I managed to get from 23 kB to 7 kB (although it's still a bit too much – that might be because of Ramda itself) by modifying package.json to force webpack into importing from `src` instead of `es`.

You can check it out yourselves:
```
// index.js
import { isNotNil } from 'ramda-extension'
console.log(isNotNil('asd'))
```
```
// package.json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@babel/core": "^7.1.0",
    "@babel/plugin-proposal-export-default-from": "^7.0.0",
    "@babel/preset-env": "^7.1.0",
    "babel-loader": "^8.0.2",
    "ramda": "^0.25.0",
    "webpack": "^4.19.1",
    "webpack-cli": "^3.1.1"
  }
}
```
```
// webpack.config.js
module.exports = {
  entry: './index.js',
  mode: 'production',
  module: {
    rules: [
      {
        test: /\.js$/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env'],
            plugins: [
              require('@babel/plugin-proposal-object-rest-spread'),
              require('@babel/plugin-proposal-export-default-from'),
            ],
          },
        },
      },
    ],
  },
}
```
Modifying `node_modules/ramda-extension/package.json`:
- currently = 30 kB
- setting `sideEffects` to `false` = 30 kB
- removing `module` and setting `main` to `src/index.js` = 30 kB
- all of the above = 7 kB

**Comment by aizerin** [comment] 2018-09-24 13:28
@wafflepie Nice. I didn't know about the bug with `module` and `main`. But we cannot point main to src/index.js since nodejs has only experimental support for es6 modules.

I'm for closing this issue. Now I see that it has no point to fork this plugin.

**Comment by tommmyy** [comment] 2018-09-24 13:40
@aizerin but shouldn't we open a new issue for build size optimization?

**Closed** 2018-09-24 19:33 UTC
